apiVersion: v1
kind: ConfigMap
metadata:
  name: tracking-service-config
  namespace: parcelpigeon
data:
  TRACKING_HTTP_ADDR: ":8002"
  TRACKING_REDIS_ADDR: "redis:6379"
  TRACKING_EXCHANGE: "parcelpigeon"
  TRACKING_QUEUE: "tracking.projector"
  TRACKING_SHIPMENTS_URL: "http://shipments-service:8000"
  TRACKING_SMTP_ADDR: "mailhog:1025"
  TRACKING_MAIL_FROM: "no-reply@parcelpigeon.test"
  TRACKING_ENABLE_CONSUMER: "true"
