apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-service
  namespace: parcelpigeon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracking-service
  template:
    metadata:
      labels:
        app: tracking-service
    spec:
      containers:
        - name: tracking-service
          image: ghcr.io/rostyslavdiachuk/tracking-service:latest
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: tracking-service-config
            - secretRef:
                name: tracking-service-secret
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
