apiVersion: v1
kind: ConfigMap
metadata:
  name: shipments-service-config
  namespace: parcelpigeon
data:
  SHIPMENTS_RABBITMQ_EXCHANGE: "parcelpigeon"
  SHIPMENTS_PUBLISH_EVENTS: "true"
  SHIPMENTS_ETA_HOURS: "72"
  SHIPMENTS_LOG_LEVEL: "INFO"
