apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipments-service
  namespace: parcelpigeon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipments-service
  template:
    metadata:
      labels:
        app: shipments-service
    spec:
      containers:
        - name: shipments-service
          image: ghcr.io/rostyslavdiachuk/shipments-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: shipments-service-config
            - secretRef:
                name: shipments-service-secret
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
