apiVersion: v1
kind: Secret
metadata:
  name: shipments-service-secret
  namespace: parcelpigeon
type: Opaque
stringData:
  SHIPMENTS_DATABASE_URL: postgresql+psycopg://parcelpigeon:parcelpigeon@postgres:5432/shipments
  SHIPMENTS_RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
