apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: parcelpigeon
type: Opaque
stringData:
  POSTGRES_USER: parcelpigeon
  POSTGRES_PASSWORD: parcelpigeon
  POSTGRES_DB: shipments
