apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    {{- include "parcelpigeon.labels" (dict "name" "web" "ctx" $) | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      {{- include "parcelpigeon.selectorLabels" "web" | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "parcelpigeon.labels" (dict "name" "web" "ctx" $) | nindent 8 }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          ports:
            - containerPort: {{ .Values.web.port }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.web.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.web.port }}
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
